#!/bin/bash

if [[ ! -d results ]]
then
	mkdir results
fi
if [[ ! -d .snakemake ]]
then
	mkdir .snakemake
fi
if [[ ! -d .tmp ]]
then 
	mkdir .tmp
fi

if [[ "$OSTYPE" == "darwin"* ]]; then
 HT="darwin"
 US="root"
else
 US=$USER
fi

if [[ "$(docker images -q reslp/phylociraptor:0.9.1 2> /dev/null)" == "" ]]; then
  echo "phylociraptor docker image does not exist, will build it first. This can take some time, please be patient."
  docker build -t reslp/phylociraptor:0.9.1 --build-arg USER_ID=$(id -u) --build-arg GROUP_ID=$(id -g) --build-arg USER=$US --build-arg GROUP=$(id -g -n $USER) --build-arg HOSTTYPE=$HT .
fi



# this needs to be set because on Linux docker created files will be owned by root by default.
unset DOCKER_USER
if [[ "$OSTYPE" == "linux-gnu" ]]; then
 DOCKER_USER="--user $(id -u):$(id -g)"
elif [[ "$OSTYPE" == "darwin"* ]]; then #nothing to be done on MacOS
 DOCKER_USER=""
fi

TMPFS="-v $(pwd)/.tmp:/tmp"
BINDPOINTS="-v $(pwd):/home/$US/phylociraptor"
docker run --rm -it $DOCKER_USER $BINDPOINTS --privileged reslp/phylociraptor:0.9.1 phylociraptor $@

#Command will look something like this:
#docker run --rm -it --user $(id -u):$(id -g) -v $(pwd):/home/$USER/phylociraptor --privileged reslp/phylociraptor:0.9.1
