[workspace]
name = "phylociraptor"
description = "The rapid phylogenomic tree calculator."
channels = ["conda-forge", "bioconda"]
platforms = ["linux-64", "linux-aarch64", "osx-64", "osx-arm64"]

[dependencies]
python = ">=3.10"
snakemake = "==6.0.2"
